### PR TITLE
Manage attribution href, logoURL and logoType

### PR DESCRIPTION
**Pull request by gryckelynck**
Extend layer.py to manage attribution information: href, logoURL and logoType.

### CODE REVIEW

**Comment by afabiani** [comment]
Can you please fix the test cases and squash the commits?

Thanks,
-A.

**Comment by gryckelynck** [comment]
I have squashed the commits.
I think that test errors with Travis come from a new type for attribution.
According to my proposal, attribution is now a python dictionary :

> { 'title': self.attribution_object.title, 
                 'width': self.attribution_object.width, 
                 'height': self.attribution_object.height, 
                 'href': self.attribution_object.href, 
                 'url': self.attribution_object.url, 
                 'type': self.attribution_object.type }

**Comment by gryckelynck** [comment]
That seems to be ok now.
I don't change the code.
It' a kind of magic?

**Comment by gryckelynck** [comment]
Should I do something else for that PR is taken into account?

**Pull request merged**
