### PR TITLE
Allow catalog to save different content types in REST calls

### PR DESCRIPTION
**Pull request by travislbrundage**

### CODE REVIEW

**Comment by harts-boundless** [comment]
1. Before merging this, we also want to set the Accept header, depending on what the server will give us in exchange for our JSON, and the Accept header should match up with what kind of parsing we are doing to the response body. I assume the caller is expecting and parsing JSON, so that we can use the same value for both headers. If we don't do this, the server is justified to send us XML or return an error

2. Regarding the test failure, note that .save() is not even in the stack frames in that traceback. So what change do you want to make to .save() to fix the test failure?

  > Traceback (most recent call last):
  >   File "/home/travis/build/boundlessgeo/gsconfig/test/catalogtests.py", line 525, in testWmsLayer
  >     available_layers = wmsstore.get_resources(available=True)
  >   File "/home/travis/build/boundlessgeo/gsconfig/src/geoserver/store.py", line 207, in get_resources
  >     xml = self.catalog.get_xml(res_url)
  >   File "/home/travis/build/boundlessgeo/gsconfig/src/geoserver/catalog.py", line 216, in get_xml
  >     raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
  > FailedRequestError: Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces/wmstest/wmsstores/wmsstore/wmslayers.xml?list=available but got a 500 status code: 
  > Could not load wms store: wmsstore:Server returned HTTP error code 504 for URL http://suite.opengeo.org/geoserver/ows?REQUEST=GetCapabilities&VERSION=1.1.1&SERVICE=WMS

3. We need to establish whether the same tests will pass without the patch in this PR. If this PR is not the cause, we still need to fix gsconfig or its tests, but we shouldn't mutate the PR to pass a test if it happens that the failure isn't due to the PR

---

To explain the background further:

There is downstream code reusing these parts of gsconfig, notably .save(). This downstream code is passing an object to .save() which serialized as JSON. However, .save() was hardcoded in gsconfig to deliver Content-Type: application/xml and Accept: application/xml (even though it accepts totally arbitrary payloads). So this downstream code was lying to the server about what it was delivering, which isn't right.

The server in question doesn't support application/xml and frankly we weren't interested in generating XML either, so the right solution was to change the relevant headers being sent.
This required changing gsconfig to allow callers of save() to specify the headers appropriate to the content those callers are passing.

The approach here was to add a keyword argument defaulting to application/xml, leaving existing behavior intact for all callers (it's unlikely that any callers are introspecting on the method signature, and if they are, they deserve to break because no sane person would use that as public interface).

I don't see any good reason this shouldn't work.

**Comment by harts-boundless** [comment]
The only test failing is testWmsLayer and that appears to be due to laggy response from a remote server (hence 504, a gateway is timing out). I think this is worth merging

**Comment by harts-boundless** [comment]
I can separately PR the Accept thing if this is merged (and we don't want to tell geoserver that we demand an XML response for no reason)

**Comment by travislbrundage** [comment]
Thanks for all the feedback. I made a new PR since you merged this one: https://github.com/boundlessgeo/gsconfig/pull/153

**Pull request merged**
