### PR TITLE
Noaa

### PR DESCRIPTION
**Pull request by qscripter**

### CODE REVIEW

**Comment by amirahav** [comment]
This reopens #160 and replaces #189

**Comment by amirahav** [comment]
@swainn most of those changes are by design, and this is marked as version 2.0 because of those breaking changes.

I'm open to adding `get_workspace`, `get_style`, `get_store` and `get_resource` but with this branch they will only be thin wrappers around `get_workspaces`, `get_styles`, `get_stores` and `get_resources`.
eg `get_workspaces('myws')[0]` or `get_workspaces(names=myws)[0]`

**Comment by swainn** [comment]
@amirahav That seems like a good idea. Better to preserve the existing functionality if there is no need to remove. I'd point out that if the goal of this PR is to simply provide Python 3 support, #189 does so without any breaking changes.

**Comment by jodygarnett** [comment]
@amirahav with version 2.0 and api change is an update to doc/model.rst needfull?

**Pull request merged**
