### PR TITLE
Add "raw" parameter to create_style

### PR DESCRIPTION
**Pull request by scottp-dpaw**
For some reason the style validation used by the GeoServer REST API is much stricter than the admin interface, and will rip out perfectly valid markup (e.g. <se:SvgParameter> tags). This exposes the optional "raw" parameter to disable validation, see https://jira.codehaus.org/browse/GEOS-3983

### CODE REVIEW

**Comment by jodygarnett** [comment]
Is it actually more strict then hitting the "validate" button?

Note we should also ensure this method has access to format (for SLD / CSS / YSLD).

**Comment by scottp-dpaw** [comment]
Ah! Turns out the markup-stripping problem I had was due to sending SLD 1.1 data (application/vnd.ogc.se+xml) with SLD 1.0 (application/vnd.ogc.sld+xml) as the Content-type. Passing it the right type pretty much rewrites the whole file, but retains the salient bits. Kinda lousy that you have to explicitly say what SLD version it is when it's right there in the header...

For posterity, an example of an SLD 1.1 file which renders fine in GeoServer (and validates fine via the admin UI):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/StyledLayerDescriptor.xsd" xmlns:se="http://www.opengis.net/se">
  <NamedLayer>
    <se:Name>test_layer</se:Name>
    <UserStyle>
      <se:Name>test_layer</se:Name>
      <se:FeatureTypeStyle>
        <se:Rule>
          <se:Name>Single symbol</se:Name>
          <se:LineSymbolizer>
            <se:Stroke>
              <se:SvgParameter name="stroke">#a06632</se:SvgParameter>
              <se:SvgParameter name="stroke-width">0.6</se:SvgParameter>
              <se:SvgParameter name="stroke-linejoin">bevel</se:SvgParameter>
              <se:SvgParameter name="stroke-linecap">square</se:SvgParameter>
            </se:Stroke>
          </se:LineSymbolizer>
        </se:Rule>
      </se:FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>
```
The same SLD 1.1 after being saved through the REST API with overwrite=True and Content-type="application/vnd.ogc.sld+xml":
```xml
<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ogc="http://www.opengis.net/ogc" xmlns:sld="http://www.opengis.net/sld" xmlns:gml="http://www.opengis.net/gml" xmlns:se="http://www.opengis.net/se"/>
```
The same SLD 1.1 after being saved through the REST API as a new object with overwrite=False and Content-type="application/vnd.ogc.sld+xml":
```xml
<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name>test_layer</sld:Name>
    <sld:UserStyle>
      <sld:Name>test_layer</sld:Name>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Rule>
          <sld:Name>Single symbol</sld:Name>
          <sld:LineSymbolizer>
            <sld:Stroke/>
          </sld:LineSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>
```
The same SLD 1.1 after being saved through the REST API with Content-type="application/vnd.ogc.se+xml":
```xml
<?xml version="1.0" encoding="UTF-8"?><sld:StyledLayerDescriptor xmlns="http://www.opengis.net/sld" xmlns:sld="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:gml="http://www.opengis.net/gml" version="1.0.0">
  <sld:NamedLayer>
    <sld:Name>test_layer</sld:Name>
    <sld:UserStyle>
      <sld:Name>test_layer</sld:Name>
      <sld:FeatureTypeStyle>
        <sld:Name>name</sld:Name>
        <sld:Rule>
          <sld:Name>Single symbol</sld:Name>
          <sld:LineSymbolizer>
            <sld:Stroke>
              <sld:CssParameter name="stroke">#a06632</sld:CssParameter>
              <sld:CssParameter name="stroke-linecap">square</sld:CssParameter>
              <sld:CssParameter name="stroke-linejoin">bevel</sld:CssParameter>
              <sld:CssParameter name="stroke-width">0.6</sld:CssParameter>
            </sld:Stroke>
          </sld:LineSymbolizer>
        </sld:Rule>
      </sld:FeatureTypeStyle>
    </sld:UserStyle>
  </sld:NamedLayer>
</sld:StyledLayerDescriptor>
```

**Comment by jodygarnett** [comment]
cool, so since I can also hack on the geoserver side on the fence is there any feedback I could of provided to make this easier? like a solid "your versions don't match" exception or something ...

And yeah if you are now content we could close this pull request.

**Comment by scottp-dpaw** [comment]
Well, my problem isn't solved by this discovery per se, as gsconfig has the Content-type hardcoded in as SLD 1.0. The raw parameter provides the same "I trust that you're submitting valid data" compromise that the admin UI does, and realistically is what I'd use instead of doing a is-it-SLD-1.0-or-1.1 submission dance for every style file.

I would agree that the style methods should be extended to support other formats; my hesitation in writing a patch is that it would be a substantial change to the way gsconfig works now, and my organization doesn't have style data in other formats to test it with.

**Comment by scottp-dpaw** [comment]
Okay I spoke too soon, just figured out that GeoServer caches the SLD version in data_dir/workspaces/xxx/styles/stylename.xml when you create the style. I'll write some kind of basic format selection thing and report back.

**Comment by garnertb** [comment]
@jodygarnett, @scottp-dpaw is this good to merge from your perspectives?  If so, @scottp-dpaw any chance you could squash and rebase?

**Comment by jodygarnett** [comment]
It looks like @scottp-dpaw is still working on it :) given the change of approach he may wish to close this pull request and open a second one ... but it is up to him.

**Comment by scottp-dpaw** [comment]
Truth be told I forgot to follow this up :P okay I did a rebase, fix should be good to go.

**Pull request merged**
